src/issu_plus/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from issu_plus.core.views import HomeView, StaffCreateView
from issu_plus.tracker.views import IssueListView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("new-staff/", StaffCreateView.as_view(), name="create_staff"),
    path("issues/", IssueListView.as_view(), name="issue_list"),
    path("", HomeView.as_view(), name="home"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/issu_plus/tracker/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from model_utils.models import StatusModel, TimeStampedModel

from .choices import STATUS, CATEGORY_CHOICES
from .managers import IssueManager

User = get_user_model()


class Issue(TimeStampedModel, StatusModel):
    STATUS = STATUS
    CATEGORY_CHOICES = CATEGORY_CHOICES

    title = models.CharField(_("title"), max_length=100, default="")
    description = models.TextField(_("description"), blank=True)
    category = models.CharField(_("category"), max_length=20, choices=CATEGORY_CHOICES)
    resolved = models.DateTimeField(
        _("resolved"), auto_now=False, auto_now_add=False, blank=True, null=True
    )
    submitter = models.ForeignKey(
        User,
        verbose_name=_("submitter"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="submitted_issues",
    )
    solver = models.ForeignKey(
        User,
        verbose_name=_("solver"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="resolved_issues",
    )

    objects = IssueManager()

    class Meta:
        verbose_name = _("issue")
        verbose_name_plural = _("issues")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("issue_detail", kwargs={"pk": self.pk})

src/issu_plus/core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, Permission
from django.contrib.messages import success
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, TemplateView

from issu_plus.tracker.models import Issue

User = get_user_model()


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_issues"] = Issue.objects.filter(status="open").order_by("-created")[:3]
        return context
    

class StaffCreateView(CreateView):
    model = User
    template_name = "core/user_form.html"
    form_class = UserCreationForm
    success_url = "/"

    def form_valid(self, form):
        response = super().form_valid(form)
        self.set_staff(form.cleaned_data["username"])
        success(self.request, _("Staff user successfuly created"))
        return response
    
    def set_staff(self, username):
        perm = Permission.objects.get(codename="view_issue")
        staff_group, _created = Group.objects.get_or_create(name="Staff")
        staff_group.permissions.set([perm])
        staff_group.save()
        user = User.objects.get(username=username)
        user.groups.add(staff_group)
        user.is_staff = True
        user.save()

src/issu_plus/tracker/views.py
from django.views.generic import ListView

from .models import Issue


class IssueListView(ListView):
    model = Issue
    ordering = "-created"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["solving_time"] = {
            "average": Issue.objects.average_solving_time(),
            "longest": Issue.objects.longest_solving_time(),
            "shortest": Issue.objects.shortest_solving_time(),
        }
        return context

src/issu_plus/core/templates/change_list.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block result_list %}
<table id="result_list">
    <thead>
        <tr>
            <th scope="col">
                <div class="text"><a>{% trans "Problem solving time" %}</a></div>
            </th>
            <th scope="col">
                <div class="text"><a>{% trans "Average" %}</a></div>
                <div class="clear"></div>
            </th>
            <th scope="col">
                <div class="text"><a>{% trans "Longest" %}</a></div>
                <div class="clear"></div>
            </th>
            <th scope="col">
                <div class="text"><a>{% trans "Shortest" %}</a></div>
                <div class="clear"></div>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="row1">
            <td></td>
            <td>{{ solving_time.average }}</td>
            <td>{{ solving_time.longest }}</td>
            <td>{{ solving_time.shortest }}</td>
        </tr>
    </tbody>
</table>
{{ block.super }}
{% endblock %}

src/issu_plus/core/templates/core/user_form.html
{% extends 'master.html' %}
{% load i18n %}

{% block body %}
    <div class="columns">
    <form action="" method="post" class="container column is-one-third">
        {% csrf_token %}
        <h1 class="title">{% trans "Create a new staff user" %}</h1>

        <div class="field">
            <label class="label" for="id_username">Username</label>
            <div class="control">
                <input class="input" name="username" maxlength="150" required="" id="id_username" type="text" value="{{ form.username.value|default:'' }}">
                <span class="help">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
            </div>
        </div>
        <div class="field">
            <label class="label" for="id_password1">{% trans "Password" %}</label>
            <div class="control">
                <input class="input" name="password1" maxlength="30" id="id_password1" type="password">
            </div>
            {% if form.errors.password1 %}<span class="help is-danger">{{ form.errors.password1 }}</span>{% endif %}
        </div>
        <div class="field">
            <label class="label" for="id_password2">{% trans "Password again" %}</label>
            <div class="control">
                <input class="input" name="password2" maxlength="30" id="id_password2" type="password">
            </div>
            {% if form.errors.password2 %}<span class="help is-danger">{{ form.errors.password2 }}</span>{% endif %}
        </div>
        <div class="control">
            <button type="submit" class="button is-link">Submit</button>
        </div>
    
    </form>
    </div>
{% endblock body %}

src/issu_plus/core/templates/home.html
{% extends 'master.html' %}
{% load i18n %}

{% block body %}
<section class="section">
    <h1 class="title">{% trans "Latests issues" %}</h1>

    <div class="columns">
        {% for issue in latest_issues %}
            <div class="column is-third">   
                <div class="card">
                    <header class="card-header">
                    <p class="card-header-title">{{ issue.title }}</p>
                </header>
                <div class="card-content">
                    <div class="content">
                        {{ issue.description }}
                    <br>
                    <hr>
                    <time datetime="{{ issue.created|date:"Y-m-d" }}">Opened: {{ issue.created }}</time>
                    </div>
                </div>
                <footer class="card-footer">

                    {% if user.is_superuser %}
                        <a href="{% url 'admin:tracker_issue_change' issue.pk %}" class="card-footer-item">Edit</a>
                        <a href="{% url 'admin:tracker_issue_delete' issue.pk %}" class="card-footer-item">Delete</a>
                    {% else %}
                        <a href="{% url 'admin:tracker_issue_change' issue.pk %}" class="card-footer-item">{% trans "View" %}</a>
                    {% endif %}
                </footer>
            </div>
            </div>
        {% endfor %}
    </div>
</section>
{% endblock body %}

src/issu_plus/core/templates/master.html
{% load i18n %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block html_title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
</head>
<body>
    <section class="hero is-warning">
      <div class="hero-head">
    <header class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="{% url 'home' %}">
            ISSU+_
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHero" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item"
               href="{% url 'issue_list' %}">
              {% trans "Tracker" %}
            </a>
            {% if user.is_superuser %}
              <a class="navbar-item"
                href="{% url 'admin:tracker_issue_add' %}">
                {% trans "New issue" %}
              </a>
              <a class="navbar-item"
                href="{% url 'create_staff' %}">
                {% trans "Create user" %}
              </a>
            {% endif %}
            <a class="navbar-item"
               href="{% url 'admin:tracker_issue_changelist' %}">
              {% trans "Admin" %}
            </a>
            {% if user.is_anonymous %}
              <a class="navbar-item"
                href="{% url 'admin:login' %}?next={{ request.path|urlencode }}">
                {% trans "Log in" %}
              </a>
            {% else %}
              <a class="navbar-item"
                href="{% url 'admin:logout' %}">
                {% trans "Log out" %}
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
    {% if messages %}
      {% for message in messages %}
        <div class="notification is-success">{{ message }}</div>
      {% endfor %}
    {% endif %}
  </div>
</section>
<section class="section">
    {% block body %}{% endblock %}
</section>
</body>
</html>

src/issu_plus/tracker/templates/tracker/issue_list.html
{% extends 'master.html' %}
{% load i18n %}

{% block body %}
    <section class="section ">
        <h1 class="title">{% trans "Tracker" %}</h1>


<table class="table" style="width: 100%">
    <thead>
        <tr class="is-selected">
            <th scope="col">
                <div class="text">{% trans "Problem solving time" %}</div>
            </th>
            <th scope="col">
                <div class="text">{% trans "Average" %}</div>
            </th>
            <th scope="col">
                <div class="text">{% trans "Longest" %}</div>
            </th>
            <th scope="col">
                <div class="text">{% trans "Shortest" %}</div>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="row1">
            <td></td>
            <td>{{ solving_time.average }}</td>
            <td>{{ solving_time.longest }}</td>
            <td>{{ solving_time.shortest }}</td>
        </tr>
    </tbody>
</table>
        
    <table class="table is-striped" style="width: 100%">
      <thead>
        <tr>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Status" %}</th>
            <th>{% trans "Category" %}</th>
            <th>{% trans "Opened" %}</th>
            <th>{% trans "Resolved" %}</th>
            <th>{% trans "Submitter" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for issue in issue_list %}
            <tr>
                <td><a href="{% url 'admin:tracker_issue_change' issue.pk %}">{{ issue.title }}</a></td>
                <td><span class="tag is-{% if issue.status == 'open' %}success{% else %}danger{% endif %}">{{ issue.status }}</span></td>
                <td>{{ issue.get_category_display }}</td>
                <td>{{ issue.created }}</td>
                <td>{{ issue.resolved|default:"" }}</td>
                <td>{{ issue.submitter|default:"" }}</td>
            </tr>
        {% empty %}
            <tr><td>{% trans "No issues found" %}</td></tr>
        {% endfor %}
      </tbody>
    </table>
    </section>
{% endblock body %}